### ISSUE TITLE
UIScrollView does not start aligned to the top for ios8 

### ISSUE THREAD

**Issue by giacaglia** [cyndibaby905/GIFRefreshControl#2]

**Comment by cyndibaby905** [comment]
Could you provide a simple repo to describe your problem? It works for me.

**Comment by dadpp** [comment]
IOS8 点容易奔溃 测试环境 8.1

**Comment by cyndibaby905** [comment]
@BaiCanLin  Please attach a simple repo to reproduce this issue.

**Comment by cyndibaby905** [comment]
@BaiCanLin  Just call `[scrollView removePullToRefresh];` in your viewController's `dealloc` method. That should work.
