### ISSUE TITLE
xcode6 bug

### ISSUE THREAD

**Issue by dadpp** [cyndibaby905/GIFRefreshControl#3]
CHGifRefreshControl[45826:1244892] **\* Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'An instance 0x7fd9baebd660 of class UIScrollView was deallocated while key value observers were still registered with it. Current observation info: <NSKeyValueObservationInfo 0x7fd9baec1360>

**Comment by cyndibaby905** [comment]
Just call `[scrollView removePullToRefresh];` in your viewController's `dealloc` method. That should work.
